config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'carts/index'
  get 'carts/create'
  get 'carts/update'
  get 'carts/destroy'
  devise_for :users
  get 'customers/index'
  get 'cart_orders/index'
  get 'search/results'
  get 'products/index'
  get 'products/about'
  get 'products/show'
  get 'inventory/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  # devise_for :members, controllers: { registrations: 'registrations' }
  ActiveAdmin.routes(self)
  resources :products
  resources :cart_orders
  resources :customers
  resources :categories
  resources :carts
  resources :users
  resources :employees
  resources :charges

  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/cart_order.rb
# frozen_string_literal: true

class CartOrder < ApplicationRecord
  has_and_belongs_to_many :products
  belongs_to :user
end

app/models/cart_order_product.rb
class CartOrderProduct < ApplicationRecord
  belongs_to :CartOrder
  belongs_to :Product
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
  validates :name, uniqueness: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  has_many :users
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/inventory.rb
# frozen_string_literal: true

class Inventory < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_and_belongs_to_many :cart_orders
  belongs_to :category
  has_many :carts
  mount_uploader :image, ImageUploader
  validates :bin, :name, uniqueness: true
  paginates_per 10

  # named_scope :paginate, ->(page, per_page) { { offset: ((page || 1) - 1) * (per_page || 10), limit: :per_page || 10 } }
end

app/models/province.rb
# frozen_string_literal: true

class Province < ApplicationRecord
  has_many :users
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_orders
  has_many :carts
  belongs_to :province, optional: true
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def index
    @carts = Cart.where('user_id = ?', current_user.id)
  end

  def create
    if !user_signed_in?

    else
      @cart = Cart.new(cart_params)

      redirect_to carts_path if @cart.save
    end
  end

  def update
    @cart = Cart.find(params[:id])

    logger.debug params.inspect

    @cart.update_attribute(:quantity, params[:cart][:quantity])

    @cart.save

    redirect_to carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    redirect_to carts_path
  end

  private

  def cart_params
    params.require(:cart).permit(:user_id, :product_id, :quantity)
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def results
    @query = params[:q]
    @products = Product.where('name LIKE ?', "%#{@query}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_orders_helper.rb
module CartOrdersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/delete.html.erb
<h1>Carts#delete</h1>
<p>Find me in app/views/carts/delete.html.erb</p>

app/views/carts/index.html.erb
<div class="menu">
  <h1>Connor Soccer Shop</h1>
  <nav>
    <ul>
      <li><%= link_to 'Home', products_path %></li>
      <li><%= link_to 'About', "/products/about" %></li>
      <li><%= link_to 'Cart', carts_path %></li>
    </ul>
  </nav>
</div>
<h2>Cart</h2>
<%totalPrice = 0%>
<% @carts.each do |cart| %>

<%= form_for(cart, local: true) do |form| %>

<table>
  <tbody>
  <tr>
    <td><%= image_tag cart.product.image.url, width: 150 %></td>
    <td><%= cart.product.name %></td>
    <%if cart.product.salePrice == nil %>
      <td>$<%= cart.product.price * cart.quantity %><% totalPrice += cart.product.price * cart.quantity %></td>
    <%else%>
      <td><span style="text-decoration: line-through">$<%= cart.product.price * cart.quantity %></span>
      <span style="color: red">$<%= cart.product.salePrice * cart.quantity %></span>
      <% totalPrice += cart.product.salePrice * cart.quantity %></td>
    <%end%>


      <td><%= form.number_field :quantity, :value => cart.quantity,in: 1.0..200.0, step: 1 %></td>
      <td><%= form.submit 'Update'%>
              <%= link_to 'Remove', cart_path(cart),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

  </tr>
  </tbody>
</table>

   <%end%>
  <%end%>

<table>
  <tbody>
  <tr>
    <td>---</td>
    <td>---</td>
    <td>Total: $<%= totalPrice %></td>
    <td>---</td>
    <td><%= link_to "Order Now", "/charges/new" %></td>

  </tr>
  </tbody>
</table>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>