config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'carts/index'
  get 'carts/create'
  get 'carts/update'
  get 'carts/destroy'
  devise_for :users
  get 'customers/index'
  get 'cart_orders/index'
  get 'search/results'
  get 'products/index'
  get 'products/about'
  get 'products/show'
  get 'inventory/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  # devise_for :members, controllers: { registrations: 'registrations' }
  ActiveAdmin.routes(self)
  resources :products
  resources :cart_orders
  resources :customers
  resources :categories
  resources :carts
  resources :users
  resources :employees
  resources :charges

  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/cart_order.rb
# frozen_string_literal: true

class CartOrder < ApplicationRecord
  has_and_belongs_to_many :products
  belongs_to :user
end

app/models/cart_order_product.rb
class CartOrderProduct < ApplicationRecord
  belongs_to :CartOrder
  belongs_to :Product
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
  validates :name, uniqueness: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  has_many :users
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/inventory.rb
# frozen_string_literal: true

class Inventory < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_and_belongs_to_many :cart_orders
  belongs_to :category
  has_many :carts
  mount_uploader :image, ImageUploader
  validates :bin, :name, uniqueness: true
  paginates_per 10

  # named_scope :paginate, ->(page, per_page) { { offset: ((page || 1) - 1) * (per_page || 10), limit: :per_page || 10 } }
end

app/models/province.rb
# frozen_string_literal: true

class Province < ApplicationRecord
  has_many :users
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_orders
  has_many :carts
  belongs_to :province, optional: true
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def index
    @carts = Cart.where('user_id = ?', current_user.id)
  end

  def create
    if !user_signed_in?

    else
      @cart = Cart.new(cart_params)

      redirect_to carts_path if @cart.save
    end
  end

  def update
    @cart = Cart.find(params[:id])

    logger.debug params.inspect

    @cart.update_attribute(:quantity, params[:cart][:quantity])

    @cart.save

    redirect_to carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    redirect_to carts_path
  end

  private

  def cart_params
    params.require(:cart).permit(:user_id, :product_id, :quantity)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  add_breadcrumb 'Home', :products_path
  add_breadcrumb 'About', '/products/about'

  def index
    @products = if params[:products] && params[:products][:isSale]
                  Product.where.not(salePrice: [nil, 0]).order(:bin).page(params[:page])
                else
                  Product.order(:bin).page(params[:page])
                end

    @categories = Category.order(:name)
  end

  def show
    @product = Product.find(params[:id])
  end

  def about
    @employees = Employee.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_orders_helper.rb
module CartOrdersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/products/_product.html.erb
<%= link_to product do %>
<div class="list">
  <h3><%= product.name %></h3>
  <p><%= product.description %></p>
  <p>Quantity: <%= product.quantity %></p>
  <p>Brand: <%= product.category.name %></p>
  <%if product.salePrice == nil%>
    <p>Price: $<%= product.price %></p>
  <%else%>
    <p>Price: <span style="text-decoration: line-through">$<%= product.price %></span><span style="color: red">$<%= product.salePrice %></span></p>
  <%end%>

  <%if product.image.present?%>
    <p><%= image_tag product.image.url, width:300 %></p>
  <%end%>
</div>
<%end%>

app/views/products/about.html.erb
<div class="menu">
  <h1>Connor Soccer Shop</h1>
  <nav>
    <ul>
      <li><%= link_to 'Home', products_path %></li>
      <li><%= link_to 'About', "/products/about" %></li>
      <li><%= link_to 'Cart', carts_path %></li>
    </ul>
  </nav>
</div>
<body>
  <%= render_breadcrumbs %>
</body>
<p>Connor Soccer Jerseys Incorporated (CSJInc.) is a Soccer Jersey distribution company to provide recreational or premier teams with on field wear. The company insists on 40 Employees. The company has been in operation for 6 years. CSJInc distributes soccer jerseys, shorts, and socks made from major manufacturers and combines them together (Kit) and sells them. CSJInc currently sells their kits through their store. Recreational soccer teams, Premier soccer teams, or any soccer players would be the target demographic.</p>
<h3>Contacts</h3>
<table>
  <tr>
    <td><b>Contact</b></td>
    <td><b>Role</b></td>
    <td><b>Phone</b></td>
  </tr>
  <% @employees.each do |employee| %>
    <tr>
      <td><%= link_to employee.name, "/employees/#{employee.id}" %></td>
      <td><%= employee.jobtitle %></td>
      <td><%= employee.phone %></td>
    </tr>
  <%end%>
</table>

app/views/products/index.html.erb
<%= form_tag(search_results_path, method: "get") do %>
      <%= label_tag(:q, "Search for:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
    <%end%>
<div class="menu">
  <h1>Connor Soccer Shop</h1>
  <nav>
    <ul>
      <li><%= link_to 'Home', products_path %></li>
      <li><%= link_to 'About', "/products/about" %></li>
      <li><%= link_to 'Cart', carts_path %></li>
    </ul>
  </nav>
</div>
<%= form_with scope: :products, method: "get", url: products_path, local: :true do |form| %>
  <%= form.label "Filter Sale" %>
  <% if params[:products]&&params[:products][:isSale] %>
      <%= form.check_box :isSale, :onclick => "this.form.submit()", :checked => true, :include_hidden => false %>
  <%else%>
      <%= form.check_box :isSale, :onclick => "this.form.submit()", :checked => false, :include_hidden => false %>
  <%end%>
  <%# <%= form.check_box :isSale, :onclick => "this.form.submit()", :checked => params[:products][:isSale], :value => true %>
  <br/>
  <%= form.label "Filter Brand" %>
  <%= form.collection_select :category_id, @categories, :id, :name, include_blank: true %>

<%end%>
<% if params[:products]&&params[:products][:isSale] %>
  <h3>Kits On Sale</h3>
<%end%>
<%= render partial: 'products/product', collection: @products %>
<%= paginate @products %>

app/views/products/show.html.erb
<div class="menu">
  <h1>Connor Soccer Shop</h1>
  <nav>
    <ul>
      <li><%= link_to 'Home', products_path %></li>
      <li><%= link_to 'About', "/products/about" %></li>
      <li><%= link_to 'Cart', carts_path %></li>
    </ul>
  </nav>
</div>
<%= render partial: 'products/product', collection: @products %>

<%= render @product %>
<%= form_with scope: :cart, url: carts_path, local: true do |form| %>
  <% if user_signed_in? %>
    <%= form.hidden_field :user_id, required: true, class: 'form-control', value:current_user.id %>
  <% else %>
    <%= form.hidden_field :user_id, required: true, class: 'form-control', value:0%>
  <% end %>
  <%= form.hidden_field :product_id, required: true, class: 'form-control', value:@product.id %>
  <%= form.hidden_field :quantity, required: true, class: 'form-control', value:1 %><br/>
  <%= form.submit "Add to Cart" %>
<% end %>